language: generic
sudo: required

env:
    global:
        - SWIFT_VERSION=5.0

matrix:
    include:
        - os: linux
          dist: xenial
          env: BADGE=linux
          addons:
              apt:
                  packages:
                      - libbsd-dev
        - os: osx
          osx_image: xcode10.1
          env: BADGE=osx
          addons:
              homebrew:
                  packages:
                      - libressl

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build

